# Generated by Django 4.0.5 on 2022-06-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('turma', models.IntegerField(verbose_name='Turma')),
                ('adjetivo', models.CharField(max_length=100, verbose_name='essa pessoa é')),
            ],
        ),
    ]
