# Generated by Django 4.0.5 on 2022-06-14 03:11

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=stdimage.models.StdImageField(default=1, force_min_size=False, upload_to='fotos', variations={'thumb': (124, 124)}, verbose_name='foto'),
            preserve_default=False,
        ),
    ]
