# Generated by Django 4.0.5 on 2022-06-15 03:34

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aluno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='fotos', variations={'thumb': (124, 124)}, verbose_name='foto'),
        ),
    ]
